name: simply_sdk
description: A new Flutter package project.
version: 0.0.3
author:

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_auth: ^1.1.2
  firebase_core: ^1.1.0
  flutter:
    sdk: flutter
  http: ^0.13.2
  path_provider: ^2.0.1
  web_socket_channel: ^2.0.0
  sembast: ^3.0.2
  uuid: ^3.0.4
  mongo_dart: ^0.7.0+2
  cloud_firestore: ^1.0.1
  sembast_cloud_firestore_type_adapters:
    git:
      url: git://github.com/tekartik/sembast_flutter_more.dart
      path: cloud_firestore_type_adapters
      ref: dart2
      version: '>=0.1.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: