name: simply_sdk
description: SDK for Apparyllis API
version: 0.4.1
author:

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  http: ^0.13.2
  path_provider: ^2.0.1
  web_socket_channel: ^2.1.0
  uuid: ^3.0.4
  mongo_dart: ^0.7.0+2
  universal_html: ^2.0.8
  cloud_firestore: ^1.0.1
  firebase_performance: ^0.7.0+9
  shared_preferences: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: