name: simply_sdk
description: SDK for Apparyllis API
version: 1.3.6

publish_to: none

environment:
    sdk: ">=2.17.0 <3.0.0"
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter
    http: ^1.0.0
    path_provider: ^2.0.1
    web_socket_channel: ^2.1.0
    uuid: ^4.4.2
    mongo_dart: ^0.10.3
    universal_html: ^2.0.8
    shared_preferences: ^2.0.8
    source_gen: ^1.2.0
    test: ^1.17.10
    logging: ^1.0.2
    universal_file: ^1.0.0
    jwt_decode: 0.3.1

dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
